[tool.black]
exclude = '(\.git|\.venv|venv|\.mypy_cache)'
include = '\.pyi?$'
line-length = 120
target-version = ['py310']


[tool.bandit]
skips = [
    "B101",     # Use of assert detected (needed for tests)
]
exclude_dirs = [".venv", "venv"]
